spring.datasource.url: jdbc:mysql://localhost:3306/search_engine
spring.datasource.username: root
spring.datasource.password: Zalman350z
spring.jpa.hibernate.ddl-auto: create-drop

application:
  sites:
    -
      url: http://www.playback.ru
      name: Playback
    -
      url: http://radiomv.ru
      name: Милицейская волна